server:
  port: 8301
spring:
  application:
    name: cloud-ribbon-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

service-url:
  user-service: http://cloud-user-service
