
server:
  port: 8505
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/cloudmall?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000
      remove-abandoned: true
      time-between-eviction-runs-millis: 60000
      log-abandoned: true
      max-pool-prepared-statement-per-connection-size: 100
  application:
    name: cloud-oauth2-service
  redis:
    database: 0
    host: localhost
    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    timeout: 100ms
#  config-location: classpath:mybaits-config.xml
mybatis:
  mapper-locations: classpath:mappers/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  endpoint:
    health:
      enabled: true


pagehelper:
  helper-dialect: mysql
  reasonable: true

