eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
server:
  port: 9901

spring:
  application:
    name: cloud-zipkin-server
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 0.5
  rabbitmq:
    addresses: amqp://localhost:5672
    username: cheng
    password: 123456