server:
  port: 8201

spring:
  sleuth:
    messaging:
      rabbit:
        enabled: true
    sampler:
      probability: 1.0
  application:
    name: cloud-user-service
#  zipkin:
#    base-url: http://localhost:9411/
  rabbitmq:
    username: cheng
    password: 123456
    host: localhost
    port: 5672
    virtual-host: /
    listener:
      direct:
        retry:            # 是否开启发布重试
          enabled: true
          max-attempts: 5
          initial-interval: 5000
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

