server:
  port: 8201

spring:
  sleuth:
    messaging:
      rabbit:
        enabled: true
    sampler:
      probability: 1.0
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mallnew?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
      remove-abandoned: true
      time-between-eviction-runs-millis: 60000
      log-abandoned: true
      max-pool-prepared-statement-per-connection-size: 100
  application:
    name: cloud-user-service
  #  zipkin:
  #    base-url: http://localhost:9411/
  rabbitmq:
    username: cheng
    password: 123456
    host: localhost
    port: 5672
    virtual-host: /
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
    enabled: true
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        min-idle: 5
        max-idle: 200
        max-wait: -1s
        max-active: 1024
#mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.mall.userservice.model
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

